### PR TITLE
fix cosmetic bug

### LINKED ISSUE #192: [PE-D][Tester C] Cosmetic problem on the display of task completion
When the task list of a patient is empty, the display of task completion on the main state is still 100%, perhaps demonstrating [no tasks] will be a better choice?

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: MatchaRRR/ped#9

### PR DESCRIPTION
**Pull request by kennethszj**
completion rate now shows "no task available" when there is no tasks instead of 0 percent or 100 percent

### CODE REVIEW

File: src/main/java/seedu/duke/data/hospital/Hospital.java [hunk 1]
```diff
@@ -159,7 +159,12 @@ public double calculateOverallCompletionRate() {
             totalTasks += taskList.getSize();
             completedTasks += taskList.getCompletedTaskCount();
         }
-        return totalTasks == 0 ? 0.0 : ((double) completedTasks / totalTasks) * 100;
+        // return -1 to indicate no tasks
+        if (totalTasks == 0) {
+            return -1.0;
+        }
```
Comment (AjayShanker-geek) [inline src/main/java/seedu/duke/data/hospital/Hospital.java:165]: This will work for now.

**Review by AjayShanker-geek — APPROVED** [review]
LGTM
